### ISSUE TITLE
When opening the app for the first time, data does not load initially

### ISSUE THREAD

**Issue by ttyler** [D8Services/flexmdm#1]
A close and reload of the app usually fixed it, else try a force quit of the App

**Comment by sgmills** [comment]
I am having this issue and I have tried everything I can think to test. I tried with the suggested API user permissions, and also tested with full administrator permissions just to rule anything out. Same behavior with both. I tried using your sample code to encode the credentials in base64, and tried just echoing to base64, both returned the same results so I assume my credentials are encoded correctly.

This is my app config:
`<dict>
	<key>serverURL</key>
	<string>$JPS_URL</string>
	<key>apiCredentials</key>
	<string>base64apiCredsHere</string>
	<key>deviceID</key>
	<string>$JSSID</string>
	<key>submitText</key>
	<string>Submit</string>
	<key>forceDataEntry</key>
	<false/>
	<key>allowErase</key>
	<false/>
	<key>isEditable</key>
	<true/>
	<key>useLDAP</key>
	<true/>
	<key>enableAssetTag</key>
	<true/>
	<key>enableUsername</key>
	<true/>
	<key>enableFullname</key>
	<false/>
	<key>enableEmail</key>
	<false/>
	<key>enableDepartment</key>
	<true/>
	<key>enableBuilding</key>
	<true/>
	<key>enableSites</key>
	<false/>
	<key>labelUsername</key>
	<string>Username:</string>
	<key>labelSites</key>
	<string>Site:</string>
	<key>labelBuilding</key>
	<string>Category:</string>
	<key>labelDepartment</key>
	<string>Department:</string>
	<key>enabledEAs</key>
	<array>
		<string>Secondary Unit</string> 
	</array>
	<key>editableEAs</key> 
	<array>
		<string>Secondary Unit</string>
	</array>
</dict>`

Here is what I see on the device:
![IMG_F39B0A7FE537-1](https://user-images.githubusercontent.com/1520833/118851587-ec60a680-b89f-11eb-9efb-78984d025e0c.jpeg)

**Comment by ttyler** [comment]
> I am having this issue and I have tried everything I can think to test. I tried with the suggested API user permissions, and also tested with full administrator permissions just to rule anything out. Same behavior with both. I tried using your sample code to encode the credentials in base64, and tried just echoing to base64, both returned the same results so I assume my credentials are encoded correctly.
> 
> This is my app config:
> `<dict> <key>serverURL</key> <string>$JPS_URL</string> <key>apiCredentials</key> <string>base64apiCredsHere</string> <key>deviceID</key> <string>$JSSID</string> <key>submitText</key> <string>Submit</string> <key>forceDataEntry</key> <false/> <key>allowErase</key> <false/> <key>isEditable</key> <true/> <key>useLDAP</key> <true/> <key>enableAssetTag</key> <true/> <key>enableUsername</key> <true/> <key>enableFullname</key> <false/> <key>enableEmail</key> <false/> <key>enableDepartment</key> <true/> <key>enableBuilding</key> <true/> <key>enableSites</key> <false/> <key>labelUsername</key> <string>Username:</string> <key>labelSites</key> <string>Site:</string> <key>labelBuilding</key> <string>Category:</string> <key>labelDepartment</key> <string>Department:</string> <key>enabledEAs</key> <array> <string>Secondary Unit</string> </array> <key>editableEAs</key> <array> <string>Secondary Unit</string> </array> </dict>`
> 
> Here is what I see on the device:
> ![IMG_F39B0A7FE537-1](https://user-images.githubusercontent.com/1520833/118851587-ec60a680-b89f-11eb-9efb-78984d025e0c.jpeg)

Hey Sam, thanks for this, were yo able to inspect the permissions for the api user? Fred has made a small app to encode the credentials, but just testing it this morning. If you want to have a chat, happy to do this. Also looking at your App Config, that looks fine, so it is not this.

**Comment by sgmills** [comment]
Success! Looks like it was something to do with how the credentials got encoded, but using the app to encode worked and I am testing now. Thank you for your help, and thank you for this project; it fills a gap that I have wanted for a long time. Excited to see what else you're planning around FlexMDM.

**Comment by freddiep1983** [comment]
> Success! Looks like it was something to do with how the credentials got encoded, but using the app to encode worked and I am testing now. Thank you for your help, and thank you for this project; it fills a gap that I have wanted for a long time. Excited to see what else you're planning around FlexMDM.

Great! The credentials encoding process is an ugly one. We could have put a function into the website to do it, but the idea of people plugging their JPS credentials into our online systems did not sit well with us. Hopefully the app mitigates the pain a little more. 
We are still very early days on this project, we actually pushed it out to meet some immediate demands for a specific customer, so any and all feedback is greatly appreciated and of course any feature requests also :)
Cheers!

**Comment by freddiep1983** [comment]
New version 1.2 now threads the URLsession request correctly and will refresh data on the fly.
